apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: myfirstpipeline
  labels:
    name: myfirstpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "myphp", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') { stage 'SIT - Build'\nopenshiftBuild(namespace:'sit',buildConfig: 'helloworld-rs', showBuildLogs: 'true')\nstage 'SIT - Deploy'\nopenshiftDeploy(namespace:'sit', deploymentConfig: 'helloworld-rs')\nstage 'SIT - Scale to 2'openshiftScale(namespace:'sit', deploymentConfig: 'helloworld-rs',replicaCount: '2')}"
  output:
  resources:
  postCommit:
